#!/usr/bin/env python3
# usage differs from git hash-object

# git1.0 hash-object.c sha1_file.c:write_sha1_file
import hashlib
import os
import sys
import zlib

_, file_type, filename = sys.argv

contents = open(filename, "rb").read()
header = '{} {}\0'.format(file_type, len(contents)).encode("raw_unicode_escape")

hasher = hashlib.sha1()
hasher.update(header)
hasher.update(contents)
sha1 = hasher.hexdigest()

sha1_filename = '.zit/objects/{}/{}'.format(sha1[:2], sha1[2:])
dirname = os.path.dirname(sha1_filename)
if not os.path.exists(dirname):
    os.mkdir(dirname)

compressed = zlib.compress(header + contents)
open(sha1_filename, 'wb').write(compressed)

print(sha1)
