#!/usr/bin/env python3

# write-tree.c
import subprocess

import index

def write_tree(entries, base):
    i = 0
    buf = b''
    while i < len(entries):
        filename, mode, rawsha1 = entries[i]

        # for directories
        if not filename.startswith(base):
            break
        filename = filename[len(base):]
        if b'/' in filename:
            filename = filename.split(b'/', 1)[0]
            num_written, sha1 = write_tree(entries[i:], base + filename + b'/')
            i += num_written
            i -= 1 # write the directory entry, but don't count it
            mode = 0o40000
            rawsha1 = bytearray.fromhex(sha1)

        buf += oct(mode)[2:].encode("raw_unicode_escape") + b" " + filename + b"\0" + rawsha1
        i += 1
    with open('.zit/tree.tmp', 'wb') as f:
        f.write(buf)
    return i, subprocess.check_output(['hash-object', 'tree', '.zit/tree.tmp']).decode().strip()

_, sha1 = write_tree(index.read_index(), b'')
print(sha1)
